//! Main application module for Codirigent.
//!
//! This module provides the core application structure, actions, and
//! window management for the Codirigent IDE.
//!
//! Requires the `gpui` feature to be enabled.

use codirigent_core::DefaultEventBus;
use codirigent_detector::{DetectorConfig, InputDetector};
use codirigent_session::DefaultSessionManager;
use gpui::{
    div, px, size, App, AppContext, Application, Bounds, Context, Entity, FocusHandle, Focusable,
    InteractiveElement, IntoElement, KeyBinding, ParentElement, Render, Styled, TitlebarOptions,
    Window, WindowBounds, WindowOptions,
};
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tracing::info;

use crate::layout::LayoutProfile;
use crate::splash_screen::brand;
use crate::theme::CodirigentTheme;
use crate::workspace::gpui::WorkspaceView;

/// Application actions module.
///
/// Contains GPUI action types generated by the `actions!` macro.
/// These are used for keyboard shortcuts and menu items.
#[allow(missing_docs)]
mod actions_impl {
    use gpui::actions;

    actions!(
        codirigent,
        [
            NewSession,
            CloseSession,
            FocusSession1,
            FocusSession2,
            FocusSession3,
            FocusSession4,
            FocusSession5,
            FocusSession6,
            FocusSession7,
            FocusSession8,
            FocusSession9,
            NextLayout,
            ToggleSidebar,
            Paste,
            Copy,
            OpenSettings,
            Quit,
        ]
    );
}

pub use actions_impl::*;

/// Default splash screen duration in milliseconds.
const DEFAULT_SPLASH_DURATION_MS: u64 = 2000;

/// Application view state.
enum AppViewState {
    /// Showing the splash screen.
    Splash { loading_message: String },
    /// Showing the main workspace.
    Workspace { workspace: Entity<WorkspaceView> },
}

/// Root application view that manages splash -> workspace transition.
pub struct AppView {
    /// Current view state.
    state: AppViewState,
    /// Focus handle.
    focus_handle: FocusHandle,
    /// Session manager reference.
    session_manager: Arc<Mutex<DefaultSessionManager>>,
    /// Input detector reference.
    detector: Arc<Mutex<InputDetector>>,
    /// Event bus reference.
    event_bus: Arc<DefaultEventBus>,
    /// Theme.
    theme: CodirigentTheme,
}

impl AppView {
    /// Create a new app view starting with splash screen.
    ///
    /// Shows the splash screen for the specified duration, then transitions
    /// to the main workspace.
    pub fn new_with_splash(
        session_manager: Arc<Mutex<DefaultSessionManager>>,
        detector: Arc<Mutex<InputDetector>>,
        event_bus: Arc<DefaultEventBus>,
        theme: CodirigentTheme,
        splash_duration: Duration,
        cx: &mut Context<Self>,
    ) -> Self {
        // Spawn a timer task that transitions to workspace after the duration.
        // Uses `async move |this, mut cx|` pattern for proper lifetime handling.
        cx.spawn(async move |this, cx| {
            cx.background_executor().timer(splash_duration).await;
            this.update(cx, |this, cx| {
                this.transition_to_workspace(cx);
            })
        })
        .detach();

        Self {
            state: AppViewState::Splash {
                loading_message: "Loading modules...".to_string(),
            },
            focus_handle: cx.focus_handle(),
            session_manager,
            detector,
            event_bus,
            theme,
        }
    }

    /// Create a new app view directly with workspace (no splash).
    pub fn new_workspace(
        session_manager: Arc<Mutex<DefaultSessionManager>>,
        detector: Arc<Mutex<InputDetector>>,
        event_bus: Arc<DefaultEventBus>,
        theme: CodirigentTheme,
        cx: &mut Context<Self>,
    ) -> Self {
        let workspace = cx.new(|cx| {
            WorkspaceView::new(
                session_manager.clone(),
                detector.clone(),
                event_bus.clone(),
                theme.clone(),
                cx,
            )
        });

        Self {
            state: AppViewState::Workspace { workspace },
            focus_handle: cx.focus_handle(),
            session_manager,
            detector,
            event_bus,
            theme,
        }
    }

    /// Transition from splash to workspace.
    fn transition_to_workspace(&mut self, cx: &mut Context<Self>) {
        let workspace = cx.new(|cx| {
            WorkspaceView::new(
                self.session_manager.clone(),
                self.detector.clone(),
                self.event_bus.clone(),
                self.theme.clone(),
                cx,
            )
        });
        self.state = AppViewState::Workspace { workspace };
        cx.notify();
    }

    /// Render a single grid cell of the logo.
    fn render_logo_cell(color: gpui::Hsla, size: f32, radius: f32) -> impl IntoElement {
        div()
            .w(px(size))
            .h(px(size))
            .rounded(px(radius))
            .bg(color)
    }

    /// Render the 3x3 grid logo.
    fn render_logo(scale: f32) -> impl IntoElement {
        let cell_size = 25.0 * scale;
        let gap = 7.0 * scale;
        let radius = 5.0 * scale;

        div()
            .flex()
            .flex_col()
            .gap(px(gap))
            .child(
                // Row 1
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::TEAL, cell_size, radius))
                    .child(Self::render_logo_cell(brand::TEAL_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::TEAL_40, cell_size, radius)),
            )
            .child(
                // Row 2
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::TEAL_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::CORAL, cell_size, radius))
                    .child(Self::render_logo_cell(brand::TEAL_70, cell_size, radius)),
            )
            .child(
                // Row 3
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::TEAL_40, cell_size, radius))
                    .child(Self::render_logo_cell(brand::TEAL_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::TEAL, cell_size, radius)),
            )
    }

    /// Render the splash screen.
    fn render_splash(&self, loading_message: &str, cx: &mut Context<Self>) -> impl IntoElement {
        let version = env!("CARGO_PKG_VERSION");

        div()
            .size_full()
            .track_focus(&self.focus_handle(cx))
            .bg(brand::BACKGROUND)
            .flex()
            .flex_col()
            .items_center()
            .justify_center()
            .relative()
            .child(
                // Glow effect container
                div()
                    .absolute()
                    .w(px(400.0))
                    .h(px(400.0))
                    .rounded_full()
                    .bg(gpui::hsla(176.0 / 360.0, 0.58, 0.55, 0.1)),
            )
            .child(
                // Main content
                div()
                    .flex()
                    .flex_col()
                    .items_center()
                    .gap_6()
                    .child(Self::render_logo(1.0))
                    .child(
                        // Wordmark with letter spacing
                        div()
                            .text_size(px(28.0))
                            .text_color(brand::TEXT)
                            .flex()
                            .flex_row()
                            .gap(px(8.0))
                            .child("C")
                            .child("O")
                            .child("D")
                            .child("I")
                            .child("R")
                            .child("I")
                            .child("G")
                            .child("E")
                            .child("N")
                            .child("T"),
                    )
                    .child(
                        div()
                            .text_size(px(12.0))
                            .text_color(brand::TEXT_MUTED)
                            .child(loading_message.to_string()),
                    ),
            )
            .child(
                div()
                    .absolute()
                    .bottom_5()
                    .text_size(px(11.0))
                    .text_color(brand::TEXT_VERY_MUTED)
                    .child(format!("v{}", version)),
            )
    }
}

impl Focusable for AppView {
    fn focus_handle(&self, _cx: &App) -> FocusHandle {
        self.focus_handle.clone()
    }
}

impl Render for AppView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        match &self.state {
            AppViewState::Splash { loading_message } => {
                self.render_splash(loading_message, cx).into_any_element()
            }
            AppViewState::Workspace { workspace } => {
                div().size_full().child(workspace.clone()).into_any_element()
            }
        }
    }
}

/// Main Codirigent application state.
///
/// Holds references to the session manager, input detector, and event bus
/// that are shared across the application.
pub struct CodirigentApp {
    /// Session manager for PTY and session lifecycle.
    pub session_manager: Arc<Mutex<DefaultSessionManager>>,
    /// Input detector for monitoring session status.
    pub detector: Arc<Mutex<InputDetector>>,
    /// Event bus for cross-module communication.
    pub event_bus: Arc<DefaultEventBus>,
    /// Application theme.
    pub theme: CodirigentTheme,
    /// Whether to show splash screen on startup.
    pub show_splash: bool,
    /// Splash screen duration.
    pub splash_duration: Duration,
}

impl CodirigentApp {
    /// Create a new application instance with default configuration.
    ///
    /// Initializes the session manager, input detector, and event bus.
    /// By default, the splash screen is enabled.
    pub fn new() -> Self {
        let event_bus = Arc::new(DefaultEventBus::new(64));

        let session_manager = Arc::new(Mutex::new(DefaultSessionManager::new(event_bus.clone())));

        let detector = Arc::new(Mutex::new(InputDetector::new(
            DetectorConfig::default(),
            event_bus.clone(),
        )));

        Self {
            session_manager,
            detector,
            event_bus,
            theme: CodirigentTheme::dark(),
            show_splash: true,
            splash_duration: Duration::from_millis(DEFAULT_SPLASH_DURATION_MS),
        }
    }

    /// Create a new application instance with a specific theme.
    pub fn with_theme(theme: CodirigentTheme) -> Self {
        let mut app = Self::new();
        app.theme = theme;
        app
    }

    /// Enable or disable the splash screen.
    pub fn with_splash(mut self, show: bool) -> Self {
        self.show_splash = show;
        self
    }

    /// Set the splash screen duration.
    pub fn with_splash_duration(mut self, duration: Duration) -> Self {
        self.splash_duration = duration;
        self
    }

    /// Run the GPUI application.
    ///
    /// This starts the application event loop and opens the main window.
    /// If splash screen is enabled, it shows the splash first before
    /// transitioning to the workspace.
    /// This method does not return until the application is closed.
    pub fn run(self) {
        info!("Starting Codirigent GPUI application...");

        let show_splash = self.show_splash;
        let splash_duration = self.splash_duration;

        Application::new().run(move |cx: &mut App| {
            // Register global actions
            Self::register_actions(cx);

            // Bind keyboard shortcuts to actions
            cx.bind_keys([
                KeyBinding::new("cmd-n", NewSession, None),
                KeyBinding::new("cmd-w", CloseSession, None),
                KeyBinding::new("cmd-q", Quit, None),
                KeyBinding::new("cmd-\\", NextLayout, None),
                KeyBinding::new("cmd-b", ToggleSidebar, None),
                KeyBinding::new("cmd-v", Paste, None),
                KeyBinding::new("cmd-c", Copy, None),
                KeyBinding::new("cmd-,", OpenSettings, None),
                KeyBinding::new("cmd-1", FocusSession1, None),
                KeyBinding::new("cmd-2", FocusSession2, None),
                KeyBinding::new("cmd-3", FocusSession3, None),
                KeyBinding::new("cmd-4", FocusSession4, None),
                KeyBinding::new("cmd-5", FocusSession5, None),
                KeyBinding::new("cmd-6", FocusSession6, None),
                KeyBinding::new("cmd-7", FocusSession7, None),
                KeyBinding::new("cmd-8", FocusSession8, None),
                KeyBinding::new("cmd-9", FocusSession9, None),
            ]);

            // Create the main window
            let session_manager = self.session_manager.clone();
            let detector = self.detector.clone();
            let event_bus = self.event_bus.clone();
            let theme = self.theme.clone();

            // Use Zed's default window size (1536x864) for a comfortable default
            let default_layout = LayoutProfile::Grid2x2;
            let (min_width, min_height) = default_layout.minimum_window_size();

            let bounds = Bounds::centered(None, size(px(1536.0), px(864.0)), cx);

            if show_splash {
                // Show splash screen with transition to workspace
                cx.open_window(
                    WindowOptions {
                        window_bounds: Some(WindowBounds::Windowed(bounds)),
                        window_min_size: Some(size(px(min_width), px(min_height))),
                        titlebar: Some(TitlebarOptions {
                            title: Some("Codirigent".into()),
                            appears_transparent: true,  // Custom titlebar like Zed
                            traffic_light_position: None,
                            ..Default::default()
                        }),
                        ..Default::default()
                    },
                    move |_window, cx| {
                        cx.new(|cx| {
                            AppView::new_with_splash(
                                session_manager,
                                detector,
                                event_bus,
                                theme,
                                splash_duration,
                                cx,
                            )
                        })
                    },
                )
                .expect("Failed to open main window");
            } else {
                // Skip splash, go directly to workspace
                cx.open_window(
                    WindowOptions {
                        window_bounds: Some(WindowBounds::Windowed(bounds)),
                        window_min_size: Some(size(px(min_width), px(min_height))),
                        titlebar: Some(TitlebarOptions {
                            title: Some("Codirigent".into()),
                            appears_transparent: true,  // Custom titlebar like Zed
                            traffic_light_position: None,
                            ..Default::default()
                        }),
                        ..Default::default()
                    },
                    move |_window, cx| {
                        cx.new(|cx| {
                            AppView::new_workspace(session_manager, detector, event_bus, theme, cx)
                        })
                    },
                )
                .expect("Failed to open main window");
            }
        });
    }

    /// Register global application actions.
    fn register_actions(cx: &mut App) {
        cx.on_action(|_: &Quit, cx| {
            info!("Quit action triggered");
            cx.quit();
        });

        // Note: NewSession, CloseSession, NextLayout, ToggleSidebar, and
        // FocusSession1-9 are now handled by WorkspaceView's registered actions.
        // The global handlers here are fallbacks that log the action.

        cx.on_action(|_: &NewSession, _cx| {
            info!("NewSession action triggered (global fallback)");
        });

        cx.on_action(|_: &CloseSession, _cx| {
            info!("CloseSession action triggered (global fallback)");
        });

        cx.on_action(|_: &NextLayout, _cx| {
            info!("NextLayout action triggered (global fallback)");
        });

        cx.on_action(|_: &ToggleSidebar, _cx| {
            info!("ToggleSidebar action triggered (global fallback)");
        });

        // Session focus actions (global fallbacks) - use macro to reduce repetition
        macro_rules! register_focus_fallback {
            ($cx:expr, $($action:ty),+ $(,)?) => {
                $($cx.on_action(|_: &$action, _cx| {
                    info!(concat!(stringify!($action), " triggered (global fallback)"));
                });)+
            };
        }
        register_focus_fallback!(
            cx,
            FocusSession1, FocusSession2, FocusSession3,
            FocusSession4, FocusSession5, FocusSession6,
            FocusSession7, FocusSession8, FocusSession9,
        );
    }
}

impl Default for CodirigentApp {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(all(test, feature = "gpui-full"))]
mod tests {
    use super::*;

    #[test]
    fn test_dirigent_app_new() {
        let app = CodirigentApp::new();
        assert!(Arc::strong_count(&app.event_bus) >= 1);
        assert!(Arc::strong_count(&app.session_manager) == 1);
        assert!(Arc::strong_count(&app.detector) == 1);
        assert!(app.show_splash); // Splash enabled by default
    }

    #[test]
    fn test_dirigent_app_default() {
        let app = CodirigentApp::default();
        assert!(Arc::strong_count(&app.event_bus) >= 1);
    }

    #[test]
    fn test_dirigent_app_with_theme() {
        let app = CodirigentApp::with_theme(CodirigentTheme::light());
        // Light theme has different background color
        assert!(app.theme.background != CodirigentTheme::dark().background);
    }

    #[test]
    fn test_dirigent_app_with_splash() {
        let app = CodirigentApp::new().with_splash(false);
        assert!(!app.show_splash);

        let app = CodirigentApp::new().with_splash(true);
        assert!(app.show_splash);
    }

    #[test]
    fn test_dirigent_app_with_splash_duration() {
        let app = CodirigentApp::new().with_splash_duration(Duration::from_secs(5));
        assert_eq!(app.splash_duration, Duration::from_secs(5));
    }

    #[test]
    fn test_default_splash_duration() {
        let app = CodirigentApp::new();
        assert_eq!(app.splash_duration, Duration::from_millis(DEFAULT_SPLASH_DURATION_MS));
    }
}
