//! Main application module for Codirigent.
//!
//! This module provides the core application structure, actions, and
//! window management for the Codirigent IDE.
//!
//! Requires the `gpui` feature to be enabled.

use codirigent_core::hook_installer;
use codirigent_core::{DefaultEventBus, FileStorageService, StorageService};
use codirigent_detector::{DetectorConfig, InputDetector};
use codirigent_session::DefaultSessionManager;
use gpui::{
    div, point, px, size, App, AppContext, Application, Bounds, Context, Entity, FocusHandle,
    Focusable, InteractiveElement, IntoElement, KeyBinding, ParentElement, Render, Styled,
    TitlebarOptions, Window, WindowBounds, WindowOptions,
};
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tracing::{info, warn};

use crate::layout::LayoutProfile;
use crate::splash_screen::brand;
use crate::theme::CodirigentTheme;
use crate::workspace::gpui::WorkspaceView;

/// Application actions module.
///
/// Contains GPUI action types generated by the `actions!` macro.
/// These are used for keyboard shortcuts and menu items.
#[allow(missing_docs)]
mod actions_impl {
    use gpui::actions;

    actions!(
        codirigent,
        [
            NewSession,
            CloseSession,
            FocusSession1,
            FocusSession2,
            FocusSession3,
            FocusSession4,
            FocusSession5,
            FocusSession6,
            FocusSession7,
            FocusSession8,
            FocusSession9,
            NextLayout,
            ToggleSidebar,
            ToggleTaskBoard,
            QuickSwitch,
            SplitHorizontal,
            SplitVertical,
            ClosePane,
            Paste,
            Copy,
            SearchTerminal,
            OpenSettings,
            Quit,
        ]
    );
}

pub use actions_impl::*;

/// Build the complete list of default GPUI key bindings.
///
/// This function is used both at startup (to register the initial binding set)
/// and in the settings-save callback (to re-register the full default set before
/// appending user overrides). Because GPUI's `bind_keys` appends rather than
/// replaces, re-registering the complete default set before user overrides ensures
/// last-registered-wins gives a consistent snapshot on every save.
pub(crate) fn default_gpui_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("secondary-shift-n", NewSession, None),
        KeyBinding::new("secondary-alt-w", CloseSession, None),
        KeyBinding::new("secondary-q", Quit, None),
        KeyBinding::new("secondary-shift-l", NextLayout, None),
        // Ctrl/Cmd+Shift+E — toggle sidebar (repo drawer)
        KeyBinding::new("secondary-shift-e", ToggleSidebar, None),
        // Ctrl/Cmd+Shift+T — toggle task board
        KeyBinding::new("secondary-shift-t", ToggleTaskBoard, None),
        // Ctrl/Cmd+Shift+K — quick switch
        KeyBinding::new("secondary-shift-k", QuickSwitch, None),
        KeyBinding::new("secondary-v", Paste, None),
        KeyBinding::new("secondary-c", Copy, None),
        KeyBinding::new("secondary-shift-f", SearchTerminal, None),
        KeyBinding::new("secondary-alt-shift-h", SplitHorizontal, None),
        KeyBinding::new("secondary-alt-shift-v", SplitVertical, None),
        KeyBinding::new("secondary-alt-shift-w", ClosePane, None),
        KeyBinding::new("secondary-,", OpenSettings, None),
        KeyBinding::new("secondary-1", FocusSession1, None),
        KeyBinding::new("secondary-2", FocusSession2, None),
        KeyBinding::new("secondary-3", FocusSession3, None),
        KeyBinding::new("secondary-4", FocusSession4, None),
        KeyBinding::new("secondary-5", FocusSession5, None),
        KeyBinding::new("secondary-6", FocusSession6, None),
        KeyBinding::new("secondary-7", FocusSession7, None),
        KeyBinding::new("secondary-8", FocusSession8, None),
        KeyBinding::new("secondary-9", FocusSession9, None),
    ]
}

/// Default splash screen duration in milliseconds.
const DEFAULT_SPLASH_DURATION_MS: u64 = 2000;

/// Maximum window width for bounds validation (8K UHD).
const MAX_WINDOW_WIDTH: f32 = 7680.0;
/// Maximum window height for bounds validation (8K UHD).
const MAX_WINDOW_HEIGHT: f32 = 4320.0;
/// Reasonable screen coordinate limit (allows multi-monitor with negative offsets).
const MAX_WINDOW_COORDINATE: f32 = 16000.0;

/// Application view state.
enum AppViewState {
    /// Showing the splash screen.
    Splash { loading_message: String },
    /// Showing the main workspace.
    Workspace { workspace: Entity<WorkspaceView> },
}

/// Root application view that manages splash -> workspace transition.
pub struct AppView {
    /// Current view state.
    state: AppViewState,
    /// Focus handle.
    focus_handle: FocusHandle,
    /// Session manager reference.
    session_manager: Arc<Mutex<DefaultSessionManager>>,
    /// Input detector reference.
    detector: Arc<Mutex<InputDetector>>,
    /// Event bus reference.
    event_bus: Arc<DefaultEventBus>,
    /// Theme.
    theme: CodirigentTheme,
}

impl AppView {
    /// Create a new app view starting with splash screen.
    ///
    /// Shows the splash screen for the specified duration, then transitions
    /// to the main workspace.
    pub fn new_with_splash(
        session_manager: Arc<Mutex<DefaultSessionManager>>,
        detector: Arc<Mutex<InputDetector>>,
        event_bus: Arc<DefaultEventBus>,
        theme: CodirigentTheme,
        splash_duration: Duration,
        cx: &mut Context<Self>,
    ) -> Self {
        // Spawn a timer task that transitions to workspace after the duration.
        // Uses `async move |this, mut cx|` pattern for proper lifetime handling.
        cx.spawn(async move |this, cx| {
            cx.background_executor().timer(splash_duration).await;
            this.update(cx, |this, cx| {
                this.transition_to_workspace(cx);
            })
        })
        .detach();

        Self {
            state: AppViewState::Splash {
                loading_message: "Loading modules...".to_string(),
            },
            focus_handle: cx.focus_handle(),
            session_manager,
            detector,
            event_bus,
            theme,
        }
    }

    /// Create a new app view directly with workspace (no splash).
    pub fn new_workspace(
        session_manager: Arc<Mutex<DefaultSessionManager>>,
        detector: Arc<Mutex<InputDetector>>,
        event_bus: Arc<DefaultEventBus>,
        theme: CodirigentTheme,
        cx: &mut Context<Self>,
    ) -> Self {
        let workspace = cx.new(|cx| {
            WorkspaceView::new(
                session_manager.clone(),
                detector.clone(),
                event_bus.clone(),
                theme.clone(),
                cx,
            )
        });

        Self {
            state: AppViewState::Workspace { workspace },
            focus_handle: cx.focus_handle(),
            session_manager,
            detector,
            event_bus,
            theme,
        }
    }

    /// Transition from splash to workspace.
    fn transition_to_workspace(&mut self, cx: &mut Context<Self>) {
        let workspace = cx.new(|cx| {
            WorkspaceView::new(
                self.session_manager.clone(),
                self.detector.clone(),
                self.event_bus.clone(),
                self.theme.clone(),
                cx,
            )
        });
        self.state = AppViewState::Workspace { workspace };
        cx.notify();
    }

    /// Render a single grid cell of the logo.
    fn render_logo_cell(color: gpui::Hsla, size: f32, radius: f32) -> impl IntoElement {
        div().w(px(size)).h(px(size)).rounded(px(radius)).bg(color)
    }

    /// Render the 3x3 grid logo.
    fn render_logo(scale: f32) -> impl IntoElement {
        let cell_size = 25.0 * scale;
        let gap = 7.0 * scale;
        let radius = 5.0 * scale;

        div()
            .flex()
            .flex_col()
            .gap(px(gap))
            .child(
                // Row 1
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::GREEN, cell_size, radius))
                    .child(Self::render_logo_cell(brand::GREEN_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::GREEN_40, cell_size, radius)),
            )
            .child(
                // Row 2
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::GREEN_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::CORAL, cell_size, radius))
                    .child(Self::render_logo_cell(brand::GREEN_70, cell_size, radius)),
            )
            .child(
                // Row 3
                div()
                    .flex()
                    .flex_row()
                    .gap(px(gap))
                    .child(Self::render_logo_cell(brand::GREEN_40, cell_size, radius))
                    .child(Self::render_logo_cell(brand::GREEN_70, cell_size, radius))
                    .child(Self::render_logo_cell(brand::GREEN, cell_size, radius)),
            )
    }

    /// Render the splash screen.
    fn render_splash(&self, loading_message: &str, cx: &mut Context<Self>) -> impl IntoElement {
        let version = env!("CARGO_PKG_VERSION");

        div()
            .size_full()
            .track_focus(&self.focus_handle(cx))
            .bg(brand::BACKGROUND)
            .flex()
            .flex_col()
            .items_center()
            .justify_center()
            .relative()
            .child(
                // Glow effect container
                div()
                    .absolute()
                    .w(px(400.0))
                    .h(px(400.0))
                    .rounded_full()
                    .bg(brand::GLOW),
            )
            .child(
                // Main content
                div()
                    .flex()
                    .flex_col()
                    .items_center()
                    .gap_6()
                    .child(Self::render_logo(1.0))
                    .child(
                        // Wordmark with letter spacing
                        div()
                            .text_size(px(28.0))
                            .text_color(brand::TEXT)
                            .flex()
                            .flex_row()
                            .gap(px(8.0))
                            .child("C")
                            .child("O")
                            .child("D")
                            .child("I")
                            .child("R")
                            .child("I")
                            .child("G")
                            .child("E")
                            .child("N")
                            .child("T"),
                    )
                    .child(
                        div()
                            .text_size(px(12.0))
                            .text_color(brand::TEXT_MUTED)
                            .child(loading_message.to_string()),
                    ),
            )
            .child(
                div()
                    .absolute()
                    .bottom_5()
                    .text_size(px(11.0))
                    .text_color(brand::TEXT_VERY_MUTED)
                    .child(format!("v{}", version)),
            )
    }
}

impl Focusable for AppView {
    fn focus_handle(&self, _cx: &App) -> FocusHandle {
        self.focus_handle.clone()
    }
}

impl Render for AppView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        match &self.state {
            AppViewState::Splash { loading_message } => {
                self.render_splash(loading_message, cx).into_any_element()
            }
            AppViewState::Workspace { workspace } => div()
                .size_full()
                .child(workspace.clone())
                .into_any_element(),
        }
    }
}

/// Main Codirigent application state.
///
/// Holds references to the session manager, input detector, and event bus
/// that are shared across the application.
pub struct CodirigentApp {
    /// Session manager for PTY and session lifecycle.
    pub session_manager: Arc<Mutex<DefaultSessionManager>>,
    /// Input detector for monitoring session status.
    pub detector: Arc<Mutex<InputDetector>>,
    /// Event bus for cross-module communication.
    pub event_bus: Arc<DefaultEventBus>,
    /// Application theme.
    pub theme: CodirigentTheme,
    /// Whether to show splash screen on startup.
    pub show_splash: bool,
    /// Splash screen duration.
    pub splash_duration: Duration,
}

impl CodirigentApp {
    /// Create a new application instance with default configuration.
    ///
    /// Initializes the session manager, input detector, and event bus.
    /// By default, the splash screen is enabled.
    pub fn new() -> Self {
        let event_bus = Arc::new(DefaultEventBus::with_default_capacity());

        let session_manager = Arc::new(Mutex::new(DefaultSessionManager::new(event_bus.clone())));

        let detector = Arc::new(Mutex::new(InputDetector::new(
            DetectorConfig::default(),
            event_bus.clone(),
        )));

        Self {
            session_manager,
            detector,
            event_bus,
            theme: CodirigentTheme::dark(),
            show_splash: true,
            splash_duration: Duration::from_millis(DEFAULT_SPLASH_DURATION_MS),
        }
    }

    /// Create a new application instance with a specific theme.
    pub fn with_theme(theme: CodirigentTheme) -> Self {
        let mut app = Self::new();
        app.theme = theme;
        app
    }

    /// Enable or disable the splash screen.
    pub fn with_splash(mut self, show: bool) -> Self {
        self.show_splash = show;
        self
    }

    /// Set the splash screen duration.
    pub fn with_splash_duration(mut self, duration: Duration) -> Self {
        self.splash_duration = duration;
        self
    }

    /// Run the GPUI application.
    ///
    /// This starts the application event loop and opens the main window.
    /// If splash screen is enabled, it shows the splash first before
    /// transitioning to the workspace.
    /// This method does not return until the application is closed.
    pub fn run(self) {
        info!("Starting Codirigent GPUI application...");

        // Install Claude Code hooks so status detection works without manual setup.
        // Use the full path to the sibling binary so the hook runs correctly
        // regardless of whether its directory is on PATH.
        let hook_binary = hook_installer::hook_binary_path();
        match hook_installer::ensure_hooks_installed(&hook_binary) {
            Ok(true) => info!("Claude Code hooks installed ({})", hook_binary.display()),
            Ok(false) => {}
            Err(e) => warn!("Failed to install Claude Code hooks: {e}"),
        }

        match hook_installer::ensure_codex_hooks_installed(&hook_binary) {
            Ok(true) => info!("Codex hooks installed ({})", hook_binary.display()),
            Ok(false) => {}
            Err(e) => warn!("Failed to install Codex hooks: {e}"),
        }

        match hook_installer::ensure_gemini_hooks_installed(&hook_binary) {
            Ok(true) => info!("Gemini hooks installed ({})", hook_binary.display()),
            Ok(false) => {}
            Err(e) => warn!("Failed to install Gemini hooks: {e}"),
        }

        let show_splash = self.show_splash;
        let splash_duration = self.splash_duration;

        Application::new().run(move |cx: &mut App| {
            // Install platform-specific shutdown guard (macOS: adds
            // applicationShouldTerminate: to GPUI's delegate class).
            crate::platform::shutdown_guard::install();

            // Register global actions
            Self::register_actions(cx);

            // Bind keyboard shortcuts to actions.
            // "secondary-" is GPUI's platform-aware modifier: Cmd on macOS, Ctrl elsewhere.
            cx.bind_keys(default_gpui_keybindings());

            // Create the main window
            let session_manager = self.session_manager.clone();
            let detector = self.detector.clone();
            let event_bus = self.event_bus.clone();
            let theme = self.theme.clone();

            // Use Zed's default window size (1536x864) for a comfortable default
            let default_layout = LayoutProfile::Grid2x2;
            let (min_width, min_height) = default_layout.minimum_window_size();

            // Try to restore saved window bounds from disk
            let saved_window = {
                let data_dir = dirs::data_dir()
                    .map(|d| d.join("Codirigent"))
                    .unwrap_or_else(|| std::env::temp_dir().join("codirigent-fallback"));
                FileStorageService::new(&data_dir)
                    .and_then(|s| s.load_state())
                    .ok()
                    .and_then(|state| state.window_bounds)
            };

            let default_bounds = Bounds::centered(None, size(px(1536.0), px(864.0)), cx);

            let window_bounds = if let Some(ref ws) = saved_window {
                // Validate saved size and position are reasonable
                let size_ok = ws.width >= min_width
                    && ws.height >= min_height
                    && ws.width <= MAX_WINDOW_WIDTH
                    && ws.height <= MAX_WINDOW_HEIGHT;
                let position_ok = ws.x.is_finite()
                    && ws.y.is_finite()
                    && ws.x.abs() < MAX_WINDOW_COORDINATE
                    && ws.y.abs() < MAX_WINDOW_COORDINATE;

                if size_ok && position_ok {
                    let bounds = Bounds {
                        origin: point(px(ws.x), px(ws.y)),
                        size: size(px(ws.width), px(ws.height)),
                    };
                    if ws.is_maximized {
                        WindowBounds::Maximized(bounds)
                    } else {
                        WindowBounds::Windowed(bounds)
                    }
                } else {
                    WindowBounds::Windowed(default_bounds)
                }
            } else {
                WindowBounds::Windowed(default_bounds)
            };

            if show_splash {
                // Show splash screen with transition to workspace
                cx.open_window(
                    WindowOptions {
                        window_bounds: Some(window_bounds),
                        window_min_size: Some(size(px(min_width), px(min_height))),
                        titlebar: Some(TitlebarOptions {
                            title: Some("Codirigent".into()),
                            appears_transparent: true, // Custom titlebar like Zed
                            traffic_light_position: None,
                        }),
                        ..Default::default()
                    },
                    move |window, cx| {
                        Self::install_window_shutdown_guard(window);
                        cx.new(|cx| {
                            AppView::new_with_splash(
                                session_manager,
                                detector,
                                event_bus,
                                theme,
                                splash_duration,
                                cx,
                            )
                        })
                    },
                )
                .expect("Failed to open main window");
            } else {
                // Skip splash, go directly to workspace
                cx.open_window(
                    WindowOptions {
                        window_bounds: Some(window_bounds),
                        window_min_size: Some(size(px(min_width), px(min_height))),
                        titlebar: Some(TitlebarOptions {
                            title: Some("Codirigent".into()),
                            appears_transparent: true, // Custom titlebar like Zed
                            traffic_light_position: None,
                        }),
                        ..Default::default()
                    },
                    move |window, cx| {
                        Self::install_window_shutdown_guard(window);
                        cx.new(|cx| {
                            AppView::new_workspace(session_manager, detector, event_bus, theme, cx)
                        })
                    },
                )
                .expect("Failed to open main window");
            }
        });
    }

    /// Install the window-level shutdown guard (Windows only).
    ///
    /// On Windows, subclasses the HWND to intercept `WM_QUERYENDSESSION`.
    /// On other platforms, this is a no-op.
    #[allow(unused_variables)]
    fn install_window_shutdown_guard(window: &Window) {
        #[cfg(target_os = "windows")]
        {
            use raw_window_handle::HasWindowHandle;
            if let Ok(handle) = HasWindowHandle::window_handle(window) {
                if let raw_window_handle::RawWindowHandle::Win32(win32) = handle.as_raw() {
                    crate::platform::shutdown_guard::install_for_window(win32.hwnd.get());
                }
            }
        }
    }

    /// Register global application actions.
    fn register_actions(cx: &mut App) {
        cx.on_action(|_: &Quit, cx| {
            info!("Quit action triggered");
            // On macOS, mark this as a user-initiated quit so the shutdown
            // guard allows it through (vs. system shutdown/logout which
            // should be blocked when sessions are active).
            #[cfg(target_os = "macos")]
            {
                crate::platform::shutdown_guard::USER_QUIT_REQUESTED
                    .store(true, std::sync::atomic::Ordering::SeqCst);
            }
            cx.quit();
        });

        // Note: NewSession, CloseSession, NextLayout, ToggleSidebar, and
        // FocusSession1-9 are now handled by WorkspaceView's registered actions.
        // The global handlers here are fallbacks that log the action.

        cx.on_action(|_: &NewSession, _cx| {
            info!("NewSession action triggered (global fallback)");
        });

        cx.on_action(|_: &CloseSession, _cx| {
            info!("CloseSession action triggered (global fallback)");
        });

        cx.on_action(|_: &NextLayout, _cx| {
            info!("NextLayout action triggered (global fallback)");
        });

        cx.on_action(|_: &ToggleSidebar, _cx| {
            info!("ToggleSidebar action triggered (global fallback)");
        });

        cx.on_action(|_: &ToggleTaskBoard, _cx| {
            info!("ToggleTaskBoard action triggered (global fallback)");
        });

        cx.on_action(|_: &SearchTerminal, _cx| {
            info!("SearchTerminal action triggered (global fallback)");
        });

        cx.on_action(|_: &QuickSwitch, _cx| {
            info!("QuickSwitch action triggered (global fallback)");
        });

        // Session focus actions (global fallbacks) - use macro to reduce repetition
        macro_rules! register_focus_fallback {
            ($cx:expr, $($action:ty),+ $(,)?) => {
                $($cx.on_action(|_: &$action, _cx| {
                    info!(concat!(stringify!($action), " triggered (global fallback)"));
                });)+
            };
        }
        register_focus_fallback!(
            cx,
            FocusSession1,
            FocusSession2,
            FocusSession3,
            FocusSession4,
            FocusSession5,
            FocusSession6,
            FocusSession7,
            FocusSession8,
            FocusSession9,
        );
    }
}

impl Default for CodirigentApp {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(all(test, feature = "gpui-full"))]
mod tests {
    use super::*;

    #[test]
    fn test_dirigent_app_new() {
        let app = CodirigentApp::new();
        assert!(Arc::strong_count(&app.event_bus) >= 1);
        assert!(Arc::strong_count(&app.session_manager) == 1);
        assert!(Arc::strong_count(&app.detector) == 1);
        assert!(app.show_splash); // Splash enabled by default
    }

    #[test]
    fn test_dirigent_app_default() {
        let app = CodirigentApp::default();
        assert!(Arc::strong_count(&app.event_bus) >= 1);
    }

    #[test]
    fn test_dirigent_app_with_theme() {
        let app = CodirigentApp::with_theme(CodirigentTheme::light());
        // Light theme has different background color
        assert!(app.theme.background != CodirigentTheme::dark().background);
    }

    #[test]
    fn test_dirigent_app_with_splash() {
        let app = CodirigentApp::new().with_splash(false);
        assert!(!app.show_splash);

        let app = CodirigentApp::new().with_splash(true);
        assert!(app.show_splash);
    }

    #[test]
    fn test_dirigent_app_with_splash_duration() {
        let app = CodirigentApp::new().with_splash_duration(Duration::from_secs(5));
        assert_eq!(app.splash_duration, Duration::from_secs(5));
    }

    #[test]
    fn test_default_splash_duration() {
        let app = CodirigentApp::new();
        assert_eq!(
            app.splash_duration,
            Duration::from_millis(DEFAULT_SPLASH_DURATION_MS)
        );
    }

    #[test]
    fn test_secondary_modifier_bindings_are_valid_keystroke_strings() {
        // "secondary-" is GPUI's platform-aware modifier token (Cmd on macOS, Ctrl elsewhere).
        // Verify that representative binding strings are parseable by GPUI's keystroke parser.
        use gpui::Keystroke;
        assert!(Keystroke::parse("secondary-shift-n").is_ok());
        assert!(Keystroke::parse("secondary-alt-shift-h").is_ok());
        assert!(Keystroke::parse("secondary-,").is_ok());
        assert!(Keystroke::parse("secondary-shift-l").is_ok());
    }
}
